# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Ahool-pkg-zabbix-proxy

PORTNAME=	Ahool-pkg-zabbix-proxy64

CONFLICTS=
CONFLICTS+=	Ahool-pkg-zabbix-proxy
CONFLICTS+=	Ahool-pkg-zabbix-proxy4
CONFLICTS+=	Ahool-pkg-zabbix-proxy44
CONFLICTS+=	Ahool-pkg-zabbix-proxy5
CONFLICTS+=	Ahool-pkg-zabbix-proxy54
CONFLICTS+=	Ahool-pkg-zabbix-proxy6

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix64-proxy

ZABBIXINTERNALNAME=	zabbix-proxy64
ZABBIXTITLE=	Zabbix Proxy 6.4
ZABBIXVERSION=	64

.include "${MASTERDIR}/Makefile"
