# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Ahool-pkg-zabbix-agent

PORTNAME=	Ahool-pkg-zabbix-agent4

CONFLICTS=	Ahool-pkg-zabbix-agent \
		Ahool-pkg-zabbix-agent44 \
		Ahool-pkg-zabbix-agent5 \
		Ahool-pkg-zabbix-agent54 \
		Ahool-pkg-zabbix-agent6 \
		Ahool-pkg-zabbix-agent62 \
		Ahool-pkg-zabbix-agent64

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix4-agent

ZABBIXINTERNALNAME=	zabbix-agent4
ZABBIXTITLE=	Zabbix Agent 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
