# $FreeBSD

MASTERDIR=	${.CURDIR}/../Ahool-pkg-zabbix-agent

PORTNAME=	Ahool-pkg-zabbix-agent54

CONFLICTS=	Ahool-pkg-zabbix-agent \
		Ahool-pkg-zabbix-agent4 \
		Ahool-pkg-zabbix-agent44 \
		Ahool-pkg-zabbix-agent5 \
		Ahool-pkg-zabbix-agent6 \
		Ahool-pkg-zabbix-agent62 \
		Ahool-pkg-zabbix-agent64

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix54-agent

ZABBIXINTERNALNAME=	zabbix-agent54
ZABBIXTITLE=	Zabbix Agent 5.4
ZABBIXVERSION=	54

.include "${MASTERDIR}/Makefile"
