# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Ahool-pkg-zabbix-proxy

PORTNAME=	Ahool-pkg-zabbix-proxy5

CONFLICTS=	Ahool-pkg-zabbix-proxy \
		Ahool-pkg-zabbix-proxy4 \
		Ahool-pkg-zabbix-proxy44 \
		Ahool-pkg-zabbix-proxy54 \
		Ahool-pkg-zabbix-proxy6 \
		Ahool-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix5-proxy

ZABBIXINTERNALNAME=	zabbix-proxy5
ZABBIXTITLE=	Zabbix Proxy 5.0
ZABBIXVERSION=	50

.include "${MASTERDIR}/Makefile"
