# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Ahool-pkg-zabbix-proxy

PORTNAME=	Ahool-pkg-zabbix-proxy4

CONFLICTS=	Ahool-pkg-zabbix-proxy \
		Ahool-pkg-zabbix-proxy44 \
		Ahool-pkg-zabbix-proxy5 \
		Ahool-pkg-zabbix-proxy54 \
		Ahool-pkg-zabbix-proxy6 \
		Ahool-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix4-proxy

ZABBIXINTERNALNAME=	zabbix-proxy4
ZABBIXTITLE=	Zabbix Proxy 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
